### ISSUE TITLE
LiteNetLib does not respect Transport.enabled if the transport was disabled by another message within the same frame

### ISSUE THREAD

**Issue by NarryG** [MirrorNetworking/LiteNetLibTransport#1]
Certain code in Mirror (specifically the scene load code) is dependent on pausing the transport on the client/server to ensure messages don't get sent out of order. As such, there are two checks within Telepathy.
```
            // note: we need to check enabled in case we set it to false
            // when LateUpdate already started.
            // (https://github.com/vis2k/Mirror/pull/379)
            if (!enabled)
                return;

            // process a maximum amount of client messages per tick
            for (int i = 0; i < clientMaxReceivesPerTick; ++i)
            {
                // stop when there is no more message
                if (!ProcessClientMessage())
                {
                    break;
                }

                // Some messages can disable transport
                // If this is disabled stop processing message in queue
                if (!enabled)
                {
                    break;
                }
            }
```   

As it stands, this transport does not account for this. The current behavior will batch messages received while the transport is disabled, but it won't properly handle the frame boundaries (`checkMessageQueues` is set to true when the transport is disabled, so when the client/server exit their OnUpdate() poll, they'll end up checking the queue the same frame)

https://github.com/MirrorNetworking/LiteNetLibTransport/blob/master/source/LiteNetLibTransport.cs#L70

This will result in various errors when using additive scene loading, as there's race condition potential (the client can try and configure sceneobjects before the scene has fully loaded.)

There is a sample project attached to https://github.com/vis2k/Mirror/issues/2033 that can be used to verify this behavior.

**Comment by James-Frowen** [comment]
Nice find, I will fix this soon.

I will probably try to add some unit tests for cases like this to make sure it is working correctly

**Comment by James-Frowen** [comment]
This should fix it https://github.com/MirrorNetworking/LiteNetLibTransport/commit/14951f9e1a98bd206d3ed165c260198d5d3609df

I will leave this issue Open till I get around to testing it
